### ISSUE TITLE
TypeError: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by miwierzbicki** [grzesjam/SDPI-kzk-simple-output#2]
Example: `python htmlTable.py 40` (to view html form of line no. 40)
>`Traceback (most recent call last):
  File "htmlTable.py", line 32, in <module>
    nron = (href[13:])
TypeError: 'NoneType' object is not subscriptable`

The same goes for _internal.py_ file

Python version: 3.7.0
Beautiful Soup version: 4.6.3
Anaconda version: 1.9.2

**Comment by grzesjam** [comment]
Thanks for the issue
Please check if it works now, they changed a little bit html of the web page and new `<a>` appear and  my static (its not good idea, i know) numbers just were cutting last bus ID

**Comment by miwierzbicki** [comment]
Yeah, now internal.py and htmlTable.py are working. But there is an error with jarrive.py (with internal number) - I don't know if it's issued with newest commit, but AFAIK it worked few hours ago before commit: 
`>python jarrive.py l458
Traceback (most recent call last):
File "jarrive.py", line 12, in <module> with urllib.request.urlopen("http://sdip.metropoliaztm.pl/web/ml/timetable/journey/"+arg) as response:
File "D:\Anaconda\lib\urllib\request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
File "D:\Anaconda\lib\urllib\request.py", line 531, in open
    response = meth(req, response)
  File "D:\Anaconda\lib\urllib\request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "D:\Anaconda\lib\urllib\request.py", line 569, in error
    return self._call_chain(*args)
  File "D:\Anaconda\lib\urllib\request.py", line 503, in _call_chain
    result = func(*args)
  File "D:\Anaconda\lib\urllib\request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: NOT FOUND`

**Comment by grzesjam** [comment]
And it dose what i suppose to.
First you use `python3 jmain.py 6` and from you get all buses that are currently on the street then you take `kiedyid` from output and put it into jarrive.py for example `python3 jarrive.py 1391847` and you get data

**Comment by grzesjam** [comment]
(i know, the documentation and program itself should be rewritten, it doesn't produce not valid json)

**Comment by miwierzbicki** [comment]
Ok, my bad. Works as it should.
